### ISSUE TITLE
Is this compatible with SPA? or for vue-router? 

### ISSUE THREAD

**Issue by brickgale** [jeroennoten/Laravel-Prerender#18]
Recently tried implementing this package to my project which is already using VueRouter for frontend routing. I have encountered some problems, still not showing the rendered page in doing 'view source page'. Is there something I need to set up? Am I lacking something?

**Comment by brickgale** [comment]
Do I need to put `\Nutsweb\LaravelPrerender\PrerenderMiddleware` in `Kernel.php`?

**Comment by ko5ch** [comment]
> Do I need to put `\Nutsweb\LaravelPrerender\PrerenderMiddleware` in `Kernel.php`?

Hi, same problem with [same package](https://github.com/codebar-ag/laravel-prerender), how you resolve this? I don't understand what i need to do in additional.
