### ISSUE TITLE
Is there any way to auto add a url to cache for prerender.io?

### ISSUE THREAD

**Issue by brickgale** [jeroennoten/Laravel-Prerender#19]
Something like doing a `POST` request `https://prerender.io/api/add-cached-url`, if ever there are no available cached in page? I'm using vue-router btw, still not sure if the vue routing gets picked up by the `PrerenderMiddleware.php`.

**Comment by thoop** [comment]
You can send a separate request to our recache API: https://prerender.io/documentation/recache

But that shouldn't be part of this middleware. That should be separate so that you can call our recache API when a page changes on your end.

**Comment by brickgale** [comment]
Thanks @thoop. Haven't really read the docs yesterday. I thought it only is applicable on urls that are already cached.
