### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by qWici** [jeroennoten/Laravel-Prerender#26]
I installed the package and configured using prerender.io service, but it doesnt work.

Steps:
1. composer require nutsweb/laravel-prerender
2. Add service provider
```
Nutsweb\LaravelPrerender\LaravelPrerenderServiceProvider::class
```
3. Setup my token in .env
4. Publish config
5. Add path '/api/*' to blacklist
6. Add meta-tag to head of index page

Since my Vue dynamically adds og and twitter card tags - I tested it on Twitter card validator, facebook og validator - doesnt work.

Prerender.io say: "We haven't seen a request with your Prerender token yet."

**Comment by thoop** [comment]
Hi there! Could you please send us an email at support@prerender.io with the account you are using and the URL you are testing so we can help look into this more? We can help you get this resolved.

**Comment by qWici** [comment]
@thoop now looks like its works. Perhaps this was some kind of delay between the project creation and the processing of the first requests.
