### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by dyial** [JeroenNoten/Laravel-Prerender#5]
Any chance that this package can be updated for Laravel 5.1?

**Comment by JeroenNoten** [comment]
I hope I can make time for it soon! If you want to help, you are very welcome to do so. (BTW I saw your feature request on the laravel5-angular-material-starter repository.)

**Comment by jadjoubran** [comment]
Hi there!
I'm here because of [issue #32](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/32) as well.
So is there something specific that wouldn't make this work on 5.1?
Or is there a specific feature that wouldn't work out of the box on 5.1?

**Comment by Pathsofdesign** [comment]
+1 Laravel 5.1 would be great! thanks very much

**Comment by JeroenNoten** [comment]
Hey all, I found some time to upgrade the package to support Laravel 5. Let me know if it works for you! And feel free to do other suggestions.

**Comment by Pathsofdesign** [comment]
Thank you!!
