### ISSUE TITLE
implementation

### ISSUE THREAD

**Issue by tenzopro** [JeroenNoten/Laravel-Prerender#6]
For some reason I seem not to get how to implement this. I have Angularjs on frontend and Laravel 5 on backend. Pretty much done all the set up in the ".env" file. i've added the tag '<meta name="fragment" content="!">' in "layout.blade.php" which is a master page. But where do i get the prerender library/file and where should it go etc. I think i'm missing something.

**Comment by JeroenNoten** [comment]
Have you added the service provider to config/app.php too?

**Comment by tenzopro** [comment]
yes. like so:

'Nutsweb\LaravelPrerender\LaravelPrerenderServiceProvider',

**Comment by tenzopro** [comment]
sorry to be a pain but any idea as to what is going on?

**Comment by tenzopro** [comment]
done that .. so what should happen?

**Comment by JeroenNoten** [comment]
All html that usually is generated by JavaScript should now be visible directly in the source.

A simple test: put `<script>document.write('test')</script>` in a view. Then, view the source of that page while visiting using the `?_escape_fragment_=` suffix and the script should be replaced by just `test`.

**Comment by tenzopro** [comment]
Yep! That seems to have done the trick.

Went back to ensure installation was right. Did try putting "<script>document.write('test')</script>" in a view and visit the URI with "?_escape_fragment_=" suffix...so that it looks like this "example.com/?_escape_fragment_=" sure enough it says "TEST". I assume this is working then. 

Just to be sure, the page automatically adjusts the URI to this "example.com/?_escape_fragment_=#!/" ... that "=#!"  at the end. I assume this is normal? 

Thanks again

**Comment by JeroenNoten** [comment]
I don't get it. What exactly did you put in the view? You said "".

**Comment by tenzopro** [comment]
i put <script>document.write('TEST')</script> without the quotes of course...and yes i'm able to see the word "TEST" displayed on page (again without quotes). So is that the indication to say its working then? 

Another thing is that in my prerender.io account i added pages to be cached and when i click on "raw html" button to see, i notice my pages on display. So i was inclined to think it is working.

**Comment by JeroenNoten** [comment]
You have to open de source of the page (right click, view source) and verify that there are no script tags anymore, but only the word TEST.

**Comment by tenzopro** [comment]
Well, when I do that I see neither script tags nor the word TEST. I only see source of my layout.blade.php... in other word tags for the layout.blade.php html. I'm confused.

**Comment by JeroenNoten** [comment]
Yeah ok, but somewhere in the HTML is the word TEST, right..?

**Comment by tenzopro** [comment]
no mate. There is no TEST in HTML. I even put it in capitals with exclamation points to make it visibly clear but nothing at all.

**Comment by JeroenNoten** [comment]
But.. you said that you were able to see TEST displayed on the page.. Then it must be somewhere in the source, right?

**Comment by tenzopro** [comment]
Yes, I still I'm able to see the word TEST on page. But when i right click and view source i can't find it there. Tried to even look line by line, top to bottom ... can't find it. If i inspect element on the displayed word TEST i can see it between body tags only and no other tags around it.

**Comment by JeroenNoten** [comment]
Note that the suffix must be `?_escape_fragment_=`, not `?escape_fragment=`.

**Comment by thoop** [comment]
Feel free to send me an email at todd@prerender.io. I'm happy to help test and make sure things are set up correctly.

**Comment by tenzopro** [comment]
Hi @JeroenNoten, I've tried that `?_escape_fragment_=`  but same result.

**Comment by tenzopro** [comment]
Hi @thoop, thanks for getting back to me through email. Here is my configuration:

here's my `.env`:
PRERENDER_TOKEN=my_token
PRERENDER_URL=my_domain
PRERENDER_ENABLE=true

I run `require nutsweb/laravel-prerender` at the command prompt and this line was added to "require" section of `composer.json` like so:

`"nutsweb/laravel-prerender": "^2.0"`

And in `config/app.php` i have added this line:

`'Nutsweb\LaravelPrerender\LaravelPrerenderServiceProvider',`

And i did run:

`$ php artisan vendor:publish`

And this created a file `prerender.php` inside config folder like so:

`config/prerender.php`

I did not do anything to this file: add or delete

That's pretty much it.

**Comment by cihadturhan** [comment]
Sorry to bump this issue, but I'm having the similar difficulty.

I successfully installed composer dependency and installed prerender.

However, it doesn't fetch from prerender service on my localserver.

The service is working perfectly fine. When I run http://example.com:3000/http://example.com, I get the pre-rendered content however when I run it like http://example.com?_escape_fragment_=/test, it still gives me the regular website with all scripts and styles. 

My config is 
```
PRERENDER_ENABLE=true
PRERENDER_URL=http://localhost
```
@tenzopro @thoop How did you resolved it?
