### ISSUE TITLE
Regex whitelist/blacklist

### ISSUE THREAD

**Issue by GregoryClaeyssens** [JeroenNoten/Laravel-Prerender#8]
Hi,

This package speaks of using regex for whitelisting or blacklisting but this does not work.
Laravel's str_is() function is used which does not use regular expressions (only the asterix).

Regex support would be great though.

**Comment by JeroenNoten** [comment]
You're right. I removed it from the documentation. I think I am not support regular expressions, because as far as I know, all URL comparison in Laravel, and many other 3rd party packages too, use `str_is()`.
